from __future__ import annotations

import argparse
import json
import logging
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any

import pandas as pd
import yaml

from config import configure_logging
from logging_utils import log_event, new_correlation_id, output_tail, safe_command_for_log


LOGGER = logging.getLogger(__name__)

REQUIRED_COLUMNS = ["timestamps", "open", "high", "low", "close", "volume", "amount"]
DEFAULT_REPO_DIR = Path("KRONOS-MODEL")
DEFAULT_MODEL_DIR = DEFAULT_REPO_DIR / "model" / "Kronos-base"
DEFAULT_TOKENIZER_DIR = DEFAULT_REPO_DIR / "model" / "Kronos-Tokenizer-base"


class AutoFinetuneError(RuntimeError):
    pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train a Kronos auto-finetune candidate from a worker-exported CSV.")
    parser.add_argument("--dataset", required=True, help="CSV dataset generated by main_auto_finetune_worker.")
    parser.add_argument("--model-dir", required=True, help="Final candidate model directory expected by the worker.")
    parser.add_argument("--repo-dir", default=os.getenv("KRONOS_REPO_DIR", str(DEFAULT_REPO_DIR)))
    parser.add_argument("--pretrained-model-dir", default=os.getenv("KRONOS_MODEL_DIR", str(DEFAULT_MODEL_DIR)))
    parser.add_argument("--pretrained-tokenizer-dir", default=os.getenv("KRONOS_TOKENIZER_DIR", str(DEFAULT_TOKENIZER_DIR)))
    parser.add_argument("--work-dir", default=os.getenv("KRONOS_AUTOFINETUNE_WORK_DIR", "output/kronos_auto_finetune"))
    parser.add_argument("--lookback", type=int, default=int(os.getenv("KRONOS_AUTOFINETUNE_LOOKBACK", "512")))
    parser.add_argument("--pred-len", type=int, default=int(os.getenv("KRONOS_AUTOFINETUNE_PRED_LEN", os.getenv("SIGNAL_PRED_LEN", "12"))))
    parser.add_argument("--epochs", type=int, default=int(os.getenv("KRONOS_AUTOFINETUNE_BASEMODEL_EPOCHS", "3")))
    parser.add_argument("--batch-size", type=int, default=int(os.getenv("KRONOS_AUTOFINETUNE_BATCH_SIZE", "8")))
    parser.add_argument("--learning-rate", type=float, default=float(os.getenv("KRONOS_AUTOFINETUNE_LEARNING_RATE", "0.000001")))
    parser.add_argument("--num-workers", type=int, default=int(os.getenv("KRONOS_AUTOFINETUNE_NUM_WORKERS", "0")))
    parser.add_argument("--train-ratio", type=float, default=float(os.getenv("KRONOS_AUTOFINETUNE_TRAIN_RATIO", "0.7")))
    parser.add_argument("--val-ratio", type=float, default=float(os.getenv("KRONOS_AUTOFINETUNE_VAL_RATIO", "0.3")))
    parser.add_argument("--device", default=os.getenv("KRONOS_AUTOFINETUNE_DEVICE", "auto"), choices=["auto", "cpu", "cuda"])
    parser.add_argument("--timeout-minutes", type=int, default=int(os.getenv("KRONOS_AUTOFINETUNE_TIMEOUT_MINUTES", "240")))
    parser.add_argument("--dry-run", action="store_true", help="Validate inputs and write config without launching training.")
    return parser.parse_args()


def _resolve(path: str | Path) -> Path:
    return Path(path).expanduser().resolve()


def _require_model_artifacts(path: Path, label: str) -> None:
    missing = [name for name in ("config.json", "model.safetensors") if not (path / name).exists()]
    if missing:
        raise AutoFinetuneError(f"{label} is missing required artifact(s): {', '.join(missing)} at {path}")


def _validate_dataset(dataset_path: Path, *, lookback: int, pred_len: int, val_ratio: float) -> dict[str, Any]:
    if not dataset_path.exists():
        raise AutoFinetuneError(f"Dataset not found: {dataset_path}")
    df = pd.read_csv(dataset_path)
    missing = [column for column in REQUIRED_COLUMNS if column not in df.columns]
    if missing:
        raise AutoFinetuneError(f"Dataset missing required column(s): {', '.join(missing)}")
    if df.empty:
        raise AutoFinetuneError("Dataset is empty")
    timestamps = pd.to_datetime(df["timestamps"], utc=True, errors="coerce")
    if timestamps.isna().any():
        raise AutoFinetuneError("Dataset contains invalid timestamps")
    for column in REQUIRED_COLUMNS[1:]:
        values = pd.to_numeric(df[column], errors="coerce")
        if values.isna().any():
            raise AutoFinetuneError(f"Dataset column {column!r} contains non-numeric values")
    window = int(lookback) + int(pred_len) + 1
    val_rows = int(len(df) * max(0.0, min(1.0, float(val_ratio))))
    train_rows = len(df) - val_rows
    if train_rows < window or val_rows < window:
        raise AutoFinetuneError(
            "Dataset is too small for configured windows: "
            f"rows={len(df)}, train_rows={train_rows}, val_rows={val_rows}, required_window={window}"
        )
    return {
        "rows": int(len(df)),
        "start_timestamp_utc": timestamps.min().isoformat(),
        "end_timestamp_utc": timestamps.max().isoformat(),
        "required_window": window,
        "train_rows": train_rows,
        "val_rows": val_rows,
    }


def _use_cuda(device_request: str) -> bool:
    if device_request == "cpu":
        return False
    if device_request == "cuda":
        return True
    try:
        import torch

        return bool(torch.cuda.is_available())
    except Exception:  # noqa: BLE001
        return False


def _config_payload(
    *,
    dataset_path: Path,
    pretrained_model_dir: Path,
    pretrained_tokenizer_dir: Path,
    training_root: Path,
    lookback: int,
    pred_len: int,
    epochs: int,
    batch_size: int,
    learning_rate: float,
    num_workers: int,
    train_ratio: float,
    val_ratio: float,
    use_cuda: bool,
) -> dict[str, Any]:
    return {
        "data": {
            "data_path": str(dataset_path),
            "lookback_window": int(lookback),
            "predict_window": int(pred_len),
            "max_context": int(lookback),
            "clip": 5.0,
            "train_ratio": float(train_ratio),
            "val_ratio": float(val_ratio),
            "test_ratio": 0.0,
        },
        "training": {
            "tokenizer_epochs": 0,
            "basemodel_epochs": int(epochs),
            "batch_size": int(batch_size),
            "log_interval": 20,
            "num_workers": int(num_workers),
            "seed": 42,
            "tokenizer_learning_rate": 0.0002,
            "predictor_learning_rate": float(learning_rate),
            "adam_beta1": 0.9,
            "adam_beta2": 0.95,
            "adam_weight_decay": 0.1,
            "accumulation_steps": 1,
        },
        "model_paths": {
            "pretrained_tokenizer": str(pretrained_tokenizer_dir),
            "pretrained_predictor": str(pretrained_model_dir),
            "exp_name": "kronos_auto_finetuned",
            "base_path": str(training_root),
            "base_save_path": str(training_root),
            "finetuned_tokenizer": str(pretrained_tokenizer_dir),
            "tokenizer_save_name": "tokenizer",
            "basemodel_save_name": "basemodel",
        },
        "experiment": {
            "name": "kronos_auto_finetune",
            "description": "Automated instrument fine-tune candidate generated by dashboard worker",
            "use_comet": False,
            "train_tokenizer": False,
            "train_basemodel": True,
            "skip_existing": False,
            "pre_trained_tokenizer": True,
            "pre_trained_predictor": True,
        },
        "device": {
            "use_cuda": bool(use_cuda),
            "device_id": 0,
        },
        "distributed": {
            "use_ddp": False,
            "backend": "gloo",
        },
    }


def _write_config(config_path: Path, payload: dict[str, Any]) -> None:
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(yaml.safe_dump(payload, sort_keys=False, allow_unicode=True), encoding="utf-8")


def _copy_best_model(*, best_model_dir: Path, final_model_dir: Path) -> None:
    _require_model_artifacts(best_model_dir, "Fine-tuned best model")
    final_model_dir.mkdir(parents=True, exist_ok=True)
    for item in best_model_dir.iterdir():
        target = final_model_dir / item.name
        if item.is_dir():
            if target.exists():
                shutil.rmtree(target)
            shutil.copytree(item, target)
        else:
            shutil.copy2(item, target)
    _require_model_artifacts(final_model_dir, "Final candidate model")


def _run_training(*, repo_dir: Path, config_path: Path, timeout_minutes: int) -> subprocess.CompletedProcess[str]:
    script = repo_dir / "finetune_csv" / "train_sequential.py"
    if not script.exists():
        raise AutoFinetuneError(f"Kronos training script not found: {script}")
    cmd = [sys.executable, str(script), "--config", str(config_path), "--skip-tokenizer"]
    log_event(LOGGER, logging.INFO, "kronos_auto_finetune.training.start", command=safe_command_for_log(cmd))
    return subprocess.run(
        cmd,
        cwd=str(script.parent),
        text=True,
        capture_output=True,
        timeout=max(1, int(timeout_minutes)) * 60,
    )


def main() -> None:
    configure_logging(service_name="kronos_auto_finetune")
    args = parse_args()
    request_id = new_correlation_id("kft")
    started = time.perf_counter()
    try:
        dataset_path = _resolve(args.dataset)
        final_model_dir = _resolve(args.model_dir)
        repo_dir = _resolve(args.repo_dir)
        pretrained_model_dir = _resolve(args.pretrained_model_dir)
        pretrained_tokenizer_dir = _resolve(args.pretrained_tokenizer_dir)
        work_dir = _resolve(args.work_dir)
        training_root = work_dir / "training"
        config_path = work_dir / "auto_finetune_config.yaml"
        best_model_dir = training_root / "basemodel" / "best_model"

        _require_model_artifacts(pretrained_model_dir, "Pretrained Kronos model")
        _require_model_artifacts(pretrained_tokenizer_dir, "Pretrained Kronos tokenizer")
        dataset_summary = _validate_dataset(
            dataset_path,
            lookback=args.lookback,
            pred_len=args.pred_len,
            val_ratio=args.val_ratio,
        )
        use_cuda = _use_cuda(args.device)
        config = _config_payload(
            dataset_path=dataset_path,
            pretrained_model_dir=pretrained_model_dir,
            pretrained_tokenizer_dir=pretrained_tokenizer_dir,
            training_root=training_root,
            lookback=args.lookback,
            pred_len=args.pred_len,
            epochs=args.epochs,
            batch_size=args.batch_size,
            learning_rate=args.learning_rate,
            num_workers=args.num_workers,
            train_ratio=args.train_ratio,
            val_ratio=args.val_ratio,
            use_cuda=use_cuda,
        )
        _write_config(config_path, config)
        log_event(
            LOGGER,
            logging.INFO,
            "kronos_auto_finetune.config.ready",
            request_id=request_id,
            dataset_summary=dataset_summary,
            config_path=str(config_path),
            final_model_dir=str(final_model_dir),
            use_cuda=use_cuda,
        )
        if args.dry_run:
            print(json.dumps({"ok": True, "dry_run": True, "config_path": str(config_path)}, indent=2))
            return

        result = _run_training(repo_dir=repo_dir, config_path=config_path, timeout_minutes=args.timeout_minutes)
        combined_output = ((result.stdout or "") + ("\n" + result.stderr if result.stderr else "")).strip()
        log_event(
            LOGGER,
            logging.INFO if result.returncode == 0 else logging.ERROR,
            "kronos_auto_finetune.training.completed",
            request_id=request_id,
            returncode=int(result.returncode),
            output_tail=output_tail(combined_output) if result.returncode != 0 else None,
            duration_ms=int((time.perf_counter() - started) * 1000),
        )
        if result.returncode != 0:
            raise AutoFinetuneError(f"Kronos fine-tune command failed with exit code {result.returncode}: {output_tail(combined_output)}")
        _copy_best_model(best_model_dir=best_model_dir, final_model_dir=final_model_dir)
        manifest = {
            "ok": True,
            "request_id": request_id,
            "dataset_path": str(dataset_path),
            "dataset_summary": dataset_summary,
            "config_path": str(config_path),
            "training_best_model_dir": str(best_model_dir),
            "model_dir": str(final_model_dir),
            "pretrained_model_dir": str(pretrained_model_dir),
            "pretrained_tokenizer_dir": str(pretrained_tokenizer_dir),
            "duration_ms": int((time.perf_counter() - started) * 1000),
        }
        (final_model_dir / "auto_finetune_manifest.json").write_text(json.dumps(manifest, indent=2, default=str), encoding="utf-8")
        log_event(LOGGER, logging.INFO, "kronos_auto_finetune.completed", **manifest)
        print(json.dumps(manifest, indent=2, default=str))
    except Exception as exc:  # noqa: BLE001
        log_event(
            LOGGER,
            logging.ERROR,
            "kronos_auto_finetune.error",
            request_id=request_id,
            duration_ms=int((time.perf_counter() - started) * 1000),
            error_type=type(exc).__name__,
            error=str(exc),
        )
        print(f"ERROR: {exc}", file=sys.stderr)
        raise SystemExit(1)


if __name__ == "__main__":
    main()
